name: Print Only Pipeline

on:
  push:
  pull_request:

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print message 1
        run: echo "Hello from GitHub Actions"

      - name: Print message 2
        run: echo "Pipeline is working successfully"
